### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by sarahmkirk** [EtalumaSupport/LumaViewPro#115]
Indicate current protocol name somewhere 
Image file names with sequence number 
Pause and stop button instead of click protocol button again to stop protocol
At initialization goes to middle? Somewhere where you see a sample
All fields require an enter -- if possible don't require enter

**Comment by EtalumaSupport** [comment]
Many issues here. 
Indicate current protocol name somewhere- DONE
Image file names with sequence number- DONE
Pause and stop button instead of click protocol button again to stop protocol- Remove this part of the issue
At initialization goes to middle? Somewhere where you see a sample- DONE
All fields require an enter -- if possible don't require enter- #149
