### ISSUE TITLE
Adjusted Interval and Duration are often not Saved in Protocol

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#144]
It seems like a certain sequence of Labware selection, New, and Step arrow key to #1 is required for a successful Save of the time lapse parameters.

**Comment by iwaniec** [comment]
When picking a plate layout, no protocol is inherently created. You have two choices:
- New needs to be pressed and the steps for all channels with acquire selected will be created for all the wells
- A channel needs to be open in the selection (on the right) and Add will add 1 step in the protocol for that channel and its settings only.

**Comment by iwaniec** [comment]
Please close or comment after testing.

**Comment by kmcleaster** [comment]
I was working on editing a protocol, saved as new and thought this might be
what was key.

This raises the question, how do you edit a protocol by adding or deleting
channels?

I think the answer is that protocol "steps" are the product of ROI's (or
platewells) and optical channels.

I need to test the edit features for this scenario. It would be very
helpful when editing to be able to view all axis coordinates while adding /
changing /deleting steps.

**Comment by iwaniec** [comment]
Currently each 'step' is a single independent image setting for the microscope. It will create a new step that is at the current x, y, z, ill, gain, color, etc. If the current settings are not at an applicable channel (on the right hand side), no step is created. For example, if you are on microscope settings, instead of a color, no step is generated.
