### ISSUE TITLE
GUI Suggestion- Highlight non-committed values in another color.

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#195]
I just ran into the issue of "changing the number in text box, not pressing return, and not realizing that it was the old value still." 

Would it be possible to highlight the text box in blue (for example) when you start changing it, then change it back to white when you hit return?  That way it is much more obvious.  

Doesn't have to be blue, I think we need to provide some method of feedback that the value hasn't been committed so that it is more obvious to the user.   

(we also discussed having it revert back to the original value after some amount of time, like 10 secs, but I like this idea much better.)

**Comment by ericweiner** [comment]
A refinement on this-
If you click on another box, while this is still highlighted, the first one reverts back to original value.

**Comment by iwaniec** [comment]
Agreed. This is a significant UX problem.

**Comment by iwaniec** [comment]
This evenings update changed it so that:
While the text / value is edited, nothing happens
If a user presses enter, the value is validated as before
NEW: if a user changes the text and leaves the text (i.e. unfocus) the text gets validated

It doesn't have a color change as suggested but does not allow a state where the text and the value don't match once unfocused.

**Comment by ericweiner** [comment]
This sounds like a very good change.   I will test today.
