### ISSUE TITLE
Lag with long exposure

### ISSUE THREAD

**Issue by iwaniec** [EtalumaSupport/LumaViewPro#209]
LVP lags with long exposure settings on the camera. Need to fix all the places there is a time.sleep!

**Comment by gdecker1** [comment]
It seems that the lag is not caused by the time.sleep statements. Changing the multiplier on time.sleep(MULTIPLIER*exposure + 0.2) or even removing the statements altogether does not reduce/eliminate the lag.

After some testing, I found that lag only occurs on high exposure when the live scope display is on and unpaused; disconnecting the camera or pausing removes the lag entirely.

I suspect that the lag is triggered when the scope display is updated (update() in the ScopeDisplay class is called). I will continue looking into the issue.

**Comment by EtalumaSupport** [comment]
Absolute priority right now

**Comment by hickerson** [comment]
Issue is "solved" by removing histogram calculation but I am not closing it yet because the root cause is still undetermined.

**Comment by EtalumaSupport** [comment]
Tested with Jordan this morning, solved without instability.
