### ISSUE TITLE
Add button on Protocol Menu inserts rather than appends, prefer it stay Add and really Add

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#242]
Want the Add button to add the new Step after the one it is currently on at the time of the Add.

**Comment by hickerson** [comment]
Instead of to the end?

**Comment by hickerson** [comment]
As far as I can tell from testing, it does insert. I changed the (in the code) to make this a bit more clear but from testing it seems to insert. It inserts before the current positions which is why the number on the current step doesn't change. This does add a bit of a dilemma in that there is no way to insert after the current step. This would presumably require another button.

**Comment by EtalumaSupport** [comment]
Then please change the button label to say "Insert"

**Comment by hickerson** [comment]
No problem! Should it always insert before the current step or should it insert after?

**Comment by EtalumaSupport** [comment]
I thought inserting after, i.e Add was more work.  Insert to me means put it in front of where we are, Add means put it after.  So changing the button to say Insert will be accurate and fine for now.

**Comment by hickerson** [comment]
Okay then we can close.

**Comment by EtalumaSupport** [comment]
thanks!
