### ISSUE TITLE
Basler Camera Driver Fails to Load on install

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#32]
After running both the command line Windows version in the ReadMe as well as the current exe, the correct camera driver  fails to load.  Device Manager screen shot attached.
![MissingDriver](https://user-images.githubusercontent.com/74261093/120051874-5df2d000-bfd7-11eb-8b25-45c7966da624.png)

**Comment by iwaniec** [comment]
Interesting. I have tried to reproduce this issue on two newly installed windows computers and did not get this result. Two potential issues that may be contributing: (1) downloading from google drive causes some issues with checking for viruses. The software is now on the drive packaged as a single .zip file (2) This is a USB3 camera. It needs to be plugged into a USB3 port. To check, look blue plastic instead of black on the plug-in part.
