### ISSUE TITLE
protocol- run entire protocol doesn't go through entire plate

### ISSUE THREAD

**Issue by sarahmkirk** [EtalumaSupport/LumaViewPro#91]
-on default capture period and capture duration on new 96 well plate only goes back and fourth to the first 4 well plates
- with capture period 10 min and duration 24hrs only goes through 1st 6 wells on 96 well plate

**Comment by iwaniec** [comment]
When you changed the text to 10 min and 24 hours, did you press enter? With the default 0.1, 0.1 it only gets through the first 4 wells before a new scan is started.  It is currently set up to accept the change on enter but this should probably be modified. I made a similar 96 well plate and it di all the wells though I am also experience issues with lag so that will also be addressed.

**Comment by sarahmkirk** [comment]
I didn't press enter :)
